services:
  flask:
    build:
      context: ./api
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app/api
    environment:
      - FLASK_APP=api/app.py
    command: flask run --host=0.0.0.0

  front:
    build:
      context: ./front
    container_name: wildaiprint_front
    ports:
      - "8080:80"